# Generated by Django 5.1.6 on 2025-05-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0001_initial"),
        ("shop", "0012_alter_product_watched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="shop.product",
            ),
        ),
    ]
