# Generated by Django 5.1.6 on 2025-05-20 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("shop", "0016_alter_product_ram_alter_product_storage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("order", "Заказ"),
                    ("promo", "Акция"),
                    ("system", "Системное"),
                    ("personal", "Персональное"),
                    ("comment", "Комментарий"),
                    ("product_available", "Товар доступен"),
                ],
                max_length=20,
                verbose_name="Тип уведомления",
            ),
        ),
        migrations.CreateModel(
            name="ProductAvalaibilityNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "notified",
                    models.BooleanField(
                        default=False, verbose_name="Пользователь уведомлен"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="shop.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление о новом товаре",
                "verbose_name_plural": "Уведомления о новых товарах",
                "unique_together": {("user", "product")},
            },
        ),
    ]
