# Generated by Django 5.1.6 on 2025-05-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("order", "Заказ"),
                    ("promo", "Акция"),
                    ("system", "Системное"),
                    ("personal", "Персональное"),
                    ("comment", "Комментарий"),
                    ("product_available", "Товар доступен"),
                    ("loyalty_level_changed", "Изменение уровня лояльности"),
                ],
                max_length=255,
                verbose_name="Тип уведомления",
            ),
        ),
    ]
