# Generated by Django 5.1.6 on 2025-04-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="contact",
            field=models.CharField(default=89662067932, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="is_save_address",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="recipient",
            field=models.CharField(default="recipient", max_length=100),
            preserve_default=False,
        ),
    ]
