# Generated by Django 5.1.6 on 2025-04-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_shippingaddress_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
