# Generated by Django 5.1.6 on 2025-04-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_shippingaddress_is_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="title",
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
