# Generated by Django 5.1.6 on 2025-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_shippingaddress_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="zipcode",
            field=models.TextField(
                blank=True, max_length=8, null=True, verbose_name="Почтовый индекс"
            ),
        ),
    ]
