# Generated by Django 5.1.6 on 2025-04-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_shippingaddress_zipcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Аватар"
            ),
        ),
    ]
