# Generated by Django 5.1.6 on 2025-04-08 11:18

import apps.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.users.utils.get_avatar_upload_path,
                verbose_name="Аватар",
            ),
        ),
    ]
