# Generated by Django 5.1.6 on 2025-04-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_hash",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="MFA Hash"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
