# Generated by Django 5.1.6 on 2025-04-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_user_mfa_hash_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mfa_hash",
        ),
        migrations.AddField(
            model_name="profile",
            name="mfa_hash",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="MFA Hash"
            ),
        ),
    ]
