# Generated by Django 5.1.6 on 2025-04-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_user_mfa_hash_profile_mfa_hash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
        migrations.AddField(
            model_name="profile",
            name="is_mfa_enabled",
            field=models.BooleanField(default=False, verbose_name="MFA"),
        ),
    ]
