# Generated by Django 5.1.6 on 2025-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_profile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_mfa_enabled",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="mfa_hash",
        ),
        migrations.AddField(
            model_name="user",
            name="is_mfa_enabled",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="MFA"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_hash",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="MFA Hash"
            ),
        ),
    ]
