# Generated by Django 5.1.6 on 2025-04-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_profile_is_mfa_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
