# Generated by Django 5.1.6 on 2025-04-23 07:32

import django.contrib.auth.validators
from django.db import migrations, models

import apps.users.validators.password_validator


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_remove_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=255,
                validators=[apps.users.validators.password_validator.PasswordValidator],
                verbose_name="Password",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="Username",
            ),
        ),
    ]
