# Generated by Django 5.1.6 on 2025-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_user_password_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_referral",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Referral"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_referred",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Referred"
            ),
        ),
    ]
