# Generated by Django 5.1.6 on 2025-05-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_user_is_referral_user_is_referred"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_referral",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_referred",
        ),
    ]
