version: '3.8'

services:
  web:
    image: sonyakarmeva1/moly:latest
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file: ".env.docker"
    depends_on:
      - db
      - redis
      - mailpit

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres_data:/var/lib/postgresql/data
    env_file: ".env.docker"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonya moly"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

#  testdb:
#    image: postgres:13-alpine
#    env_file: ".env.docker.test"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U sonya moly" ]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  celery:
    build: .
    command: celery -A conf worker -l info
    volumes:
      - ./src:/app/src
    env_file: ".env.docker"
#    depends_on:
#      db:
#        condition: service_healthy
#      redis:
#        condition: service_healthy

  celery-beat:
    build: .
    command: celery -A conf beat -l info
    volumes:
      - ./src:/app/src
    env_file: ".env.docker"
#    depends_on:
#      db:
#        condition: service_healthy
#      redis:
#        condition: service_healthy

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres_data:
  celery_beat_data:
