version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DATABASE_URL=postgresql://sonya:sonya@db:5432/moly
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - EMAIL_HOST=mailpit
      - EMAIL_PORT=1025
    depends_on:
      - db
      - redis
      - mailpit

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: moly
      POSTGRES_USER: sonya
      POSTGRES_PASSWORD: sonya
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonya moly"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  testdb:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: moly_test
      POSTGRES_USER: sonya
      POSTGRES_PASSWORD: sonya
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sonya moly" ]
      interval: 5s
      timeout: 5s
      retries: 5

  celery:
    build: .
    command: celery -A conf worker -l info
    volumes:
      - ./src:/app/src
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://sonya:sonya@db:5432/moly
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - EMAIL_HOST=mailpit
      - EMAIL_PORT=1025
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery-beat:
    build: .
    command: celery -A conf beat -l info
    volumes:
      - ./src:/app/src
      - celery_beat_data:/app/src/conf/beat
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://sonya:sonya@db:5432/moly
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - EMAIL_HOST=mailpit
      - EMAIL_PORT=1025
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres_data:
  celery_beat_data: