# Generated by Django 5.1.6 on 2025-03-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="is_general",
            field=models.BooleanField(default=False),
        ),
    ]
