# Generated by Django 5.1.6 on 2025-03-27 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_category_created_at_category_updated_at_and_more"),
        ("subscribers", "0003_alter_subscribe_is_general"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название акции"),
                ),
                ("description", models.TextField(verbose_name="Описание акции")),
                (
                    "discount_percent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Процент (%) скидки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Начало акции"
                    ),
                ),
                ("end_date", models.DateTimeField(verbose_name="Конец акции")),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="promotions",
                        to="shop.product",
                        verbose_name="Товары по акции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Акция",
                "verbose_name_plural": "Акции",
            },
        ),
    ]
