# Generated by Django 5.1.6 on 2025-03-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0004_promotion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotion",
            old_name="description",
            new_name="message",
        ),
    ]
