# Generated by Django 5.1.6 on 2025-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0005_rename_description_promotion_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
