# Generated by Django 5.1.6 on 2025-04-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0006_promotion_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
    ]
