# Generated by Django 5.1.6 on 2025-04-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0007_alter_promotion_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promotion",
            name="email",
        ),
    ]
