# Generated by Django 5.1.6 on 2025-04-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribers", "0008_remove_promotion_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="is_general",
            field=models.BooleanField(default=True),
        ),
    ]
