# Generated by Django 5.1.6 on 2025-03-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("5", "Отлично"),
                            ("4", "Хорошо"),
                            ("3", "Средне"),
                            ("2", "Плохо"),
                            ("1", "Очень плохо"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Оценка",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Наименование категории"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/%Y/%m/%d/",
                        verbose_name="Изображение категории",
                    ),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="shop.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Наименование товара"
                    ),
                ),
                ("price", models.FloatField(verbose_name="Цена товара")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "watched",
                    models.IntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0, verbose_name="Количество товара на складе"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Скоро здесь будет описание товара...",
                        verbose_name="Описание товара",
                    ),
                ),
                (
                    "info",
                    models.TextField(
                        default="Дополнительная информация о товаре",
                        verbose_name="Информация о товаре",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Slug товара"
                    ),
                ),
                ("size", models.IntegerField(default=30, verbose_name="Размер в мм")),
                (
                    "color",
                    models.TextField(
                        default="Стандартный",
                        max_length=30,
                        verbose_name="Цвет/Материал",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        default="Apple", max_length=150, verbose_name="Бренд товара"
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступны к заказу"),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="shop.category",
                        verbose_name="Категория товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["available", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/", verbose_name="Изображение"
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False, verbose_name="Основное изображение"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
    ]
