# Generated by Django 5.1.6 on 2025-03-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_rename_galeria_gallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="shop.category",
                verbose_name="Категория товара",
            ),
        ),
    ]
