# Generated by Django 5.1.6 on 2025-03-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(verbose_name="Цена товара"),
        ),
    ]
