# Generated by Django 5.1.6 on 2025-03-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
