# Generated by Django 5.1.6 on 2025-03-31 08:14

import apps.shop.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_category_created_at_category_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                upload_to=apps.shop.utils.get_category_upload_path,
                verbose_name="Изображение категории",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ImageField(
                upload_to=apps.shop.utils.get_image_upload_path,
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default=None, verbose_name="Описание товара"),
        ),
        migrations.AlterField(
            model_name="product",
            name="info",
            field=models.TextField(default=None, verbose_name="Информация о товаре"),
        ),
    ]
