# Generated by Django 5.1.6 on 2025-03-31 08:52

from django.db import migrations, models

import apps.shop.utils


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_category_image_alter_gallery_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Наименование бренда"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.shop.utils.get_brand_upload_path,
                        verbose_name="Изображение бренда",
                    ),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
                "ordering": ["title"],
            },
        ),
    ]
