# Generated by Django 5.1.6 on 2025-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="previous_price",
            field=models.IntegerField(
                blank=True, editable=False, null=True, verbose_name="Предыдущая цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Описание товара"),
        ),
        migrations.AlterField(
            model_name="product",
            name="info",
            field=models.TextField(verbose_name="Информация о товаре"),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(verbose_name="Количество товара на складе"),
        ),
        migrations.AlterField(
            model_name="product",
            name="watched",
            field=models.IntegerField(verbose_name="Количество просмотров"),
        ),
    ]
