# Generated by Django 5.1.6 on 2025-03-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_review_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("5", "Отлично"),
                    ("4", "Хорошо"),
                    ("3", "Средне"),
                    ("2", "Плохо"),
                    ("1", "Очень плохо"),
                ],
                max_length=20,
                null=True,
                verbose_name="Оценка",
            ),
        ),
    ]
