# Generated by Django 5.1.6 on 2025-04-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_product_previous_price_alter_product_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="published",
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.TextField(verbose_name="Цвет/Материал"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
