# Generated by Django 5.1.6 on 2025-04-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_remove_review_published_alter_product_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(verbose_name="Цена товара"),
        ),
    ]
