# Generated by Django 5.1.6 on 2025-04-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="watched",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Количество просмотров"
            ),
        ),
    ]
