# Generated by Django 5.1.6 on 2025-03-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_mail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mail",
            old_name="mail",
            new_name="email",
        ),
    ]
