# Generated by Django 5.1.6 on 2025-05-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_product_watched"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cpu_type",
            field=models.CharField(
                blank=True,
                choices=[("M1", "M1"), ("M2", "M2"), ("Intel", "Intel")],
                null=True,
                verbose_name="Процессор",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ram",
            field=models.CharField(
                choices=[("8GB", "8GB"), ("16GB", "16GB"), ("32GB", "32GB")],
                default="8GB",
                verbose_name="Оперативная память",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="storage",
            field=models.CharField(
                choices=[
                    ("64GB", "64GB"),
                    ("128GB", "128GB"),
                    ("256GB", "256GB"),
                    ("512GB", "512GB"),
                    ("1T", "1T"),
                ],
                default="64GB",
                verbose_name="Накопитель",
            ),
        ),
    ]
