# Generated by Django 5.1.6 on 2025-05-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_product_cpu_type_product_ram_product_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cpu_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M1", "M1"),
                    ("M2", "M2"),
                    ("M3", "M3"),
                    ("M4", "M4"),
                    ("Intel", "Intel"),
                ],
                null=True,
                verbose_name="Процессор",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ram",
            field=models.CharField(
                blank=True,
                choices=[("8GB", "8GB"), ("16GB", "16GB"), ("32GB", "32GB")],
                default="8GB",
                null=True,
                verbose_name="Оперативная память",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="storage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("64GB", "64GB"),
                    ("128GB", "128GB"),
                    ("256GB", "256GB"),
                    ("512GB", "512GB"),
                    ("1T", "1T"),
                ],
                default="64GB",
                null=True,
                verbose_name="Накопитель",
            ),
        ),
    ]
