# Generated by Django 5.1.6 on 2025-05-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_alter_product_ram_alter_product_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="ram",
            field=models.CharField(
                blank=True,
                choices=[
                    ("8GB", "8GB"),
                    ("16GB", "16GB"),
                    ("24GB", "24GB"),
                    ("32GB", "32GB"),
                    ("64GB", "64GB"),
                ],
                null=True,
                verbose_name="Оперативная память",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="storage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("64GB", "64GB"),
                    ("128GB", "128GB"),
                    ("256GB", "256GB"),
                    ("512GB", "512GB"),
                    ("1T", "1TB"),
                ],
                null=True,
                verbose_name="Накопитель",
            ),
        ),
    ]
