# Generated by Django 5.1.6 on 2025-05-02 18:44

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.referral.models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userreferral",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userreferral",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активная ссылка"),
        ),
        migrations.AddField(
            model_name="userreferral",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Завершено"), ("R", "Отклонено")],
                default="C",
                max_length=1,
                verbose_name="Вознаграждение выдано",
            ),
        ),
        migrations.AddField(
            model_name="userreferral",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ReferralLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True,
                        default=apps.referral.models.generate_token,
                        editable=False,
                        unique=True,
                        verbose_name="Токен",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 5, 9, 18, 44, 26, 538834, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="Дата окончания действия",
                    ),
                ),
                (
                    "clicks",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество переходов"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Реферальная ссылка",
                "verbose_name_plural": "Реферальные ссылки",
            },
        ),
    ]
