# Generated by Django 5.1.6 on 2025-05-05 06:52

import datetime

from django.db import migrations, models

import apps.referral.models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0002_userreferral_created_at_userreferral_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referrallink",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 12, 6, 52, 18, 4704, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата окончания действия",
            ),
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="token",
            field=models.CharField(
                default=apps.referral.models.generate_token,
                unique=True,
                verbose_name="Токен",
            ),
        ),
    ]
