# Generated by Django 5.1.6 on 2025-05-05 06:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0003_alter_referrallink_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referrallink",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 12, 6, 57, 39, 588222, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата окончания действия",
            ),
        ),
    ]
