# Generated by Django 5.1.6 on 2025-05-05 07:15

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0004_alter_referrallink_expires_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="referrallink",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 12, 7, 15, 16, 543721, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата окончания действия",
            ),
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="referred",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referred_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Приглашенный",
            ),
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Амбассадор",
            ),
        ),
    ]
