# Generated by Django 5.1.6 on 2025-05-05 07:21

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0005_alter_referrallink_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userreferral",
            options={
                "verbose_name": "Реферальная связь",
                "verbose_name_plural": "Реферальные связи",
            },
        ),
        migrations.RemoveField(
            model_name="userreferral",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="referrallink",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 12, 7, 21, 54, 336160, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата окончания действия",
            ),
        ),
    ]
