# Generated by Django 5.1.6 on 2025-05-05 09:30

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0006_alter_userreferral_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referrallink",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 12, 9, 30, 53, 45713, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата окончания действия",
            ),
        ),
    ]
