# Generated by Django 5.1.6 on 2025-05-06 10:40

import apps.referral.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0012_alter_referrallink_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referrallink",
            name="expires_at",
            field=models.DateTimeField(
                default=apps.referral.models.get_default_expires_at,
                verbose_name="Дата окончания действия",
            ),
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="status",
            field=models.CharField(
                choices=[("P", "В ожидании"), ("C", "Завершено"), ("R", "Отклонено")],
                default="C",
                max_length=1,
                verbose_name="Вознаграждение выдано",
            ),
        ),
    ]
