# Generated by Django 5.1.6 on 2025-03-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("favs", "0001_initial"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoriteproducts",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite",
                to="shop.product",
                verbose_name="Товар",
            ),
        ),
    ]
