# Generated by Django 5.1.6 on 2025-05-05 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
        ("referral", "0007_alter_referrallink_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="referral_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupons",
                to="referral.referrallink",
            ),
        ),
    ]
