# Generated by Django 5.1.6 on 2025-05-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_coupon_referral_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="referral_link",
        ),
    ]
