# Generated by Django 5.1.6 on 2025-05-13 13:23

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0006_alter_coupon_user"),
        ("shop", "0016_alter_product_ram_alter_product_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="shop.category", verbose_name="Категории со скидкой"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("personal", "Персональный промокод"),
                    ("general", "Общий промокод"),
                ],
                default="general",
                max_length=20,
                verbose_name="Тип промокода",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="min_order_amount",
            field=models.IntegerField(
                default=1000, verbose_name="Минимальная сумма заказа"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="products",
            field=models.ManyToManyField(
                blank=True, to="shop.product", verbose_name="Товары со скидкой"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Код промокода"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Размер скидки",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен ли промокод"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 5, 13))
                ],
                verbose_name="Дата начала действия",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 5, 13))
                ],
                verbose_name="Дата окончания действия",
            ),
        ),
    ]
