# Generated by Django 5.1.6 on 2025-05-14 13:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0007_coupon_categories_coupon_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("personal", "Персональный промокод"),
                    ("general", "Общий промокод"),
                    ("birthday", "День рождения"),
                    ("promo", "Промо акция"),
                    ("big_order", "Скидка за крупный заказ"),
                    ("loyalty", "Скидка за общую сумму покупок"),
                ],
                default="general",
                max_length=20,
                verbose_name="Тип промокода",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 5, 14))
                ],
                verbose_name="Дата начала действия",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 5, 14))
                ],
                verbose_name="Дата окончания действия",
            ),
        ),
    ]
