# Generated by Django 5.1.6 on 2025-05-20 18:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0008_coupon_is_used_alter_coupon_discount_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 5, 20))
                ],
                verbose_name="Дата начала действия",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 5, 20))
                ],
                verbose_name="Дата окончания действия",
            ),
        ),
    ]
