# Generated by Django 5.1.6 on 2025-05-24 05:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0010_alter_coupon_valid_from_alter_coupon_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 5, 24))
                ],
                verbose_name="Дата начала действия",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2025, 5, 24))
                ],
                verbose_name="Дата окончания действия",
            ),
        ),
    ]
