# Generated by Django 5.1.6 on 2025-06-04 11:53

import apps.coupons.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0012_alter_coupon_valid_from_alter_coupon_valid_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        apps.coupons.models.get_today
                    )
                ],
                verbose_name="Дата начала действия",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        apps.coupons.models.get_today
                    )
                ],
                verbose_name="Дата окончания действия",
            ),
        ),
    ]
