# Generated by Django 5.1.6 on 2025-05-21 09:40

import apps.loyalty.utils.get_loyalty_level_icon_path
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cashback", "0006_cashbackbalance_total_cashback_earned_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название уровня"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="Идентификатор"
                    ),
                ),
                (
                    "cashback_percentage",
                    models.IntegerField(default=0, verbose_name="Процент кэшбэка"),
                ),
                (
                    "min_points",
                    models.PositiveIntegerField(
                        verbose_name="Минимальное количество баллов"
                    ),
                ),
                (
                    "max_points",
                    models.PositiveIntegerField(
                        verbose_name="Максимальное количество баллов"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.loyalty.utils.get_loyalty_level_icon_path.get_loyalty_level_icon_path,
                        verbose_name="Значок уровня",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание уровня"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Уровень лояльности",
                "verbose_name_plural": "Уровни лояльности",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Privilege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название привилегии"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание привилегии"
                    ),
                ),
                (
                    "loyalty_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privileges",
                        to="loyalty.loyaltylevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привилегия",
                "verbose_name_plural": "Привилегии",
            },
        ),
        migrations.CreateModel(
            name="UserLoyalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Общая сумма покупок",
                    ),
                ),
                (
                    "total_cashback_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Общая сумма кэшбэка",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "cashback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty",
                        to="cashback.cashbackbalance",
                    ),
                ),
                (
                    "current_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="loyalty.loyaltylevel",
                        verbose_name="Текущий уровень лояльности",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уровень лояльности пользователя",
                "verbose_name_plural": "Уровни лояльности пользователей",
            },
        ),
    ]
