# Generated by Django 5.1.6 on 2025-05-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userloyalty",
            name="total_cashback_earned",
        ),
    ]
