# Generated by Django 5.1.6 on 2025-05-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0002_remove_userloyalty_total_cashback_earned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userloyalty",
            name="total_spent",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Общая сумма покупок"
            ),
        ),
    ]
