# Generated by Django 5.1.6 on 2025-05-21 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0004_alter_userloyalty_current_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userloyalty",
            name="current_level",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="loyalty.loyaltylevel",
                verbose_name="Текущий уровень лояльности",
            ),
        ),
    ]
