# Generated by Django 5.1.6 on 2025-05-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0006_alter_userloyalty_current_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="privilege",
            name="loyalty_level",
        ),
        migrations.AddField(
            model_name="privilege",
            name="loyalty_level",
            field=models.ManyToManyField(
                related_name="privileges",
                to="loyalty.loyaltylevel",
                verbose_name="Уровень лояльности",
            ),
        ),
    ]
