# Generated by Django 5.1.6 on 2025-03-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baskets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketproduct",
            name="quantity",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
