# Generated by Django 5.1.6 on 2025-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baskets", "0002_alter_basketproduct_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketproduct",
            name="quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
