# Generated by Django 5.1.6 on 2025-03-24 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baskets", "0003_alter_basketproduct_quantity"),
        ("shop", "0003_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket_product",
                to="shop.product",
            ),
        ),
    ]
