# Generated by Django 5.1.6 on 2025-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baskets", "0006_alter_basket_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="contact",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Контакты"
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="recipient",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Получатель"
            ),
        ),
    ]
