# Generated by Django 5.1.6 on 2025-03-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="orderproduct",
            options={
                "ordering": ("-id",),
                "verbose_name": "Товар заказа",
                "verbose_name_plural": "Товары заказа",
            },
        ),
    ]
