# Generated by Django 5.1.6 on 2025-03-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_options_alter_orderproduct_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_cost",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
