# Generated by Django 5.1.6 on 2025-04-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_total_cost_order_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
    ]
