# Generated by Django 5.1.6 on 2025-04-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_save_address",
            field=models.BooleanField(default=True),
        ),
    ]
