# Generated by Django 5.1.6 on 2025-04-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_is_save_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="recipient",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
