# Generated by Django 5.1.6 on 2025-04-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="recipient",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
