# Generated by Django 5.1.6 on 2025-04-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderproduct",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
