# Generated by Django 5.1.6 on 2025-04-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_orderproduct_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
