# Generated by Django 5.1.6 on 2025-04-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_order_stripe_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("paid", "Оплачен"),
                    ("failed", "Ошибка оплаты"),
                    ("refunded", "Возврат"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
