# Generated by Django 5.1.6 on 2025-04-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_remove_order_is_paid_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
