# Generated by Django 5.1.6 on 2025-05-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cashback_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_used",
            field=models.BooleanField(default=False),
        ),
    ]
