# Generated by Django 5.1.6 on 2025-05-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_order_cashback_used_order_coupon_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cashback_amount",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Сумма использованного кэшбека"
            ),
        ),
    ]
