# Generated by Django 5.1.6 on 2025-05-06 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0013_order_is_paid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cashback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cashback_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма кэшбэка"
                    ),
                ),
                (
                    "cashback_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("approved", "Одобрен"),
                            ("rejected", "Отклонен"),
                            ("refunded", "Возвращен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус кэшбэка",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashback",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashback",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кэшбэк",
                "verbose_name_plural": "Кэшбэки",
            },
        ),
    ]
