# Generated by Django 5.1.6 on 2025-05-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashback", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashback",
            name="cashback_amount",
        ),
        migrations.AddField(
            model_name="cashback",
            name="amount",
            field=models.PositiveIntegerField(default=0, verbose_name="Сумма кэшбэка"),
        ),
    ]
