# Generated by Django 5.1.6 on 2025-05-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashback", "0003_cashbackbalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashbackbalance",
            name="total",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
