# Generated by Django 5.1.6 on 2025-05-06 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashback", "0004_alter_cashbackbalance_total"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cashbackbalance",
            options={
                "verbose_name": "Баланс кэшбэка",
                "verbose_name_plural": "Балансы кэшбэка",
            },
        ),
        migrations.AlterField(
            model_name="cashback",
            name="cashback_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("approved", "Одобрен"),
                    ("rejected", "Отклонен"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус кэшбэка",
            ),
        ),
        migrations.AlterField(
            model_name="cashbackbalance",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cashback_balance",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
