# Generated by Django 5.1.6 on 2025-05-21 09:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashback", "0005_alter_cashbackbalance_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbackbalance",
            name="total_cashback_earned",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Всего заработано кэшбэка",
            ),
        ),
        migrations.AddField(
            model_name="cashbackbalance",
            name="total_cashback_used",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Всего использовано кэшбэка",
            ),
        ),
        migrations.AlterField(
            model_name="cashbackbalance",
            name="total",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Доступно кэшбэка"
            ),
        ),
    ]
