# Generated by Django 5.1.6 on 2025-05-24 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashback", "0006_cashbackbalance_total_cashback_earned_and_more"),
        ("orders", "0015_order_cashback_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashback",
            name="type",
            field=models.CharField(
                choices=[
                    ("birthday", "День рождения"),
                    ("referral", "Реферальный"),
                    ("purchase", "Покупка"),
                    ("promotion", "Акция"),
                    ("other", "Прочее"),
                ],
                default="purchase",
                max_length=255,
                verbose_name="Тип кэшбэка",
            ),
        ),
        migrations.AlterField(
            model_name="cashback",
            name="cashback_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("approved", "Одобрен"),
                    ("rejected", "Отклонен"),
                ],
                default="pending",
                max_length=255,
                verbose_name="Статус кэшбэка",
            ),
        ),
        migrations.AlterField(
            model_name="cashback",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cashback",
                to="orders.order",
                verbose_name="Заказ",
            ),
        ),
    ]
