# Generated by Django 5.1.6 on 2025-05-24 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashback", "0006_cashbackbalance_total_cashback_earned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashback",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 23, 15, 37, 0, 470212, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата истечения срока действия",
            ),
        ),
        migrations.AddField(
            model_name="cashback",
            name="is_expired",
            field=models.BooleanField(default=False, verbose_name="Истек ли срок"),
        ),
        migrations.AddField(
            model_name="cashbackbalance",
            name="last_expiry_check",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последняя проверка истечения"
            ),
        ),
    ]
