# Generated by Django 5.1.6 on 2025-05-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cashback", "0007_cashback_expiry_date_cashback_is_expired_and_more"),
        ("cashback", "0007_cashback_type_alter_cashback_cashback_status_and_more"),
    ]

    operations = []
