# Generated by Django 5.1.6 on 2025-06-04 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashback", "0008_merge_20250528_1803"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashback",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 4, 11, 48, 54, 564119, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата истечения срока действия",
            ),
        ),
    ]
