# Generated by Django 5.1.6 on 2025-06-04 11:53

import apps.cashback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashback", "0009_alter_cashback_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashback",
            name="expiry_date",
            field=models.DateTimeField(
                default=apps.cashback.models.update_expire_date,
                verbose_name="Дата истечения срока действия",
            ),
        ),
    ]
